version: "3"

services:
  huawei-lte-watchdog:
    privileged: true
    restart: unless-stopped
    network_mode: host
    container_name: huawei-lte-watchdog
    image: krax1337/huawei-lte-watchdog:1.0.3
    environment:
      REBOOT_TIME: "07:30"
      LTE_CELL: "12345678"
      LTE_BANDS: "1+3+7+20"
      LTE_CHANGE_TYPE: "SEQ"
      LTE_ADDRESS: "http://192.168.8.1"
      LTE_USER: "admin"
      LTE_PASSWORD: "12345678"
      TZ: "Asia/Omsk"